name = "Triton"
author = "Alexciao"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8bcc889315d752fcf513eb5cd08cfa3fe2059f2dc40d8fd45ce779443571951e"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
