name = "Triton"
author = "Alexciao"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f7f0c574b248afafaedc7ae27caaf3d9ffd0e5d287c2450feda4618538f82673"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
