name = "Triton"
author = "Alexciao"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c3a96be43e9ab5e22a9ff1383cc4710ff9c0d4ec284c763d6197f6738e65aea"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"

[options]
acceptable-game-versions = ["26.1", "26.1.1"]
